### ISSUE TITLE
Hardcoded bitcoin wallet?

### ISSUE THREAD

**Issue by JKolios** [alexellis/spotminer#1]
In main.go the address of an extant (according to blockchain.net) bitcoin account is passed as the `-u` argument to the bitcoin miner. According to the alexellis/mine-with-docker docs, this option sets the payout wallet, so all the income generated by running this will be transferred to whoever owns this wallet.

**Comment by alexellis** [comment]
I open-sourced this today and converted the config settings to YAML. What I forgot to do was to make the wallet configurable and left the test one there. I've pushed changes up so that you can set it in the YAML file. As explained on the comments of HN - this was unintentional and you can now set it up before you begin.
